language: node_js
notifications:
  on_success: never
  on_failure: never
node_js:
  - "stable"
before_script:
  - npm run typescript:build
script:
  - npm run coverage
after_success:
  - npm run coveralls